font_family		family="JetBrainsMono Nerd Font"
font_size 		11.0
background_opacity 	0.95
linux_display_server 	wayland
window_margin_width 	4
tab_bar_style 		powerline
tab_powerline_style 	round
hide_window_decorations yes
enabled_layouts 	Tall,*
remember_window_size	yes
initial_window_width	180c
initial_window_height	40c
cursor_trail		1
copy_on_select		yes

# Keybinds
map kitty_mod+enter new_window_with_cwd

# BEGIN_KITTY_THEME
# Black Metal
include current-theme.conf
# END_KITTY_THEME
