# Set default prefix to Ctrl-a
# set -g prefix Ctrl-a

# Split panes vertically using v
bind v split-window -h

# Split panes horizontally using h
bind h split-window -v

# unbind default split keys
unbind '"'
unbind %

# Resize panes using Shift + Arrow keys (5 cells at a time)
bind -r H resize-pane -L 5
bind -r J resize-pane -R 5
bind -r K resize-pane -D 5
bind -r L resize-pane -R 5

# Switch to last window
bind-key -n C-Space last-window
