#!/usr/bin/env bash

echo "Cleaning up neovim cache and state..."

rm -rf $HOME/.cache/nvim/
rm -rf $HOME/.local/state/nvim/
rm -rf $HOME/.local/share/nvim/
rm -rf $HOME/.config/nvim

sleep 2

echo "Cleanup complete."
