#!/usr/bin/env bash

set -euo pipefail

echo "Cleaning up neovim cache and state..."

echo "Cleaning .cache/nvim"
rm -rf $HOME/.cache/nvim/

echo "Cleaning .local/state/nvim"
rm -rf $HOME/.local/state/nvim/

echo "Cleaning .local/share/nvim"
rm -rf $HOME/.local/share/nvim/

echo "Cleaning .config/nvim"
rm -rf $HOME/.config/nvim

sleep 2

echo "Cleanup complete."
